#!/bin/bash
echo "==================== Seteo ===================="
gcc -c dos2unix.c
gcc main_dos2unix.c dos2unix.o -o 22u
gcc -c unix2dos.c
gcc main_unix2dos.c unix2dos.o -o u22

gcc testFiles/creadorDeTest.c -o testFiles/cdt
./testFiles/cdt

echo  "Compilation complete."
CantPruebas=5
RED="\e[31m";
GREEN="\e[32m";
MAGENTA="\e[35m"
DEFAULT="\e[97m";

echo -e "$MAGENTA\0==================== Unix2Dos ====================$DEFAULT\0"
i=1
while [ $i -le $CantPruebas ]
do
	./u22 -i testFiles/testCase$i -o testFiles/testCaseRes$i
	DIFF=$(diff testFiles/testCaseSol$i  testFiles/testCaseRes$i) 
	if [ "$DIFF" == "" ] 
	then
	    echo -e "Test $i $GREEN\0Ok$DEFAULT"
	fi

	if [ "$DIFF" != "" ] 
	then
	    echo -e "Test $i $RED\0Fallo$DEFAULT"
	fi
	i=$(( $i + 1 ))
done

echo -e "$MAGENTA\0==============Dos2Unix=============$DEFAULT\0"
i=1
while [ $i -le $CantPruebas ]
do
	./22u -o testFiles/testCaseRes2.$i -i testFiles/testCaseSol$i
	DIFF=$(diff testFiles/testCase$i  testFiles/testCaseRes2.$i) 
	if [ "$DIFF" == "" ] 
	then
	    echo -e "Test $i $GREEN\0OK$DEFAULT\0"
	fi

	if [ "$DIFF" != "" ] 
	then
	    echo -e "Test $i $RED\0Fallo$DEFAULT\0"
	fi
	i=$(( $i + 1 ))
done
