#!/bin/bash
echo "==================== Seteo ===================="

gcc testFiles/creadorDeTest.c -o testFiles/cdt
./testFiles/cdt

echo  "Complete Compilation."

# Test counter
CantPruebas=5

# Definition of colors
RED="\e[31m";
GREEN="\e[32m";
MAGENTA="\e[35m"
DEFAULT="\e[97m";

echo -e "$MAGENTA"
echo -e "==================== Unix2Dos ===================="
echo -e "$DEFAULT"
i=1
while [ $i -le $CantPruebas ]
do
        cat testFiles/testCase$i | ./unix2dos > testFiles/testCaseRes$i
        DIFF=$(diff testFiles/testCaseSol$i  testFiles/testCaseRes$i)
        if [ "$DIFF" == "" ]
        then
            echo -e "Test $i $GREEN"
	    echo -e "Ok"
	    echo -e "$DEFAULT"
        fi

        if [ "$DIFF" != "" ]
        then
            echo -e "Test $i $RED"
	    echo -e "Ok"
	    echo -e "$DEFAULT"
        fi
        i=$(( $i + 1 ))
done
echo -e "$MAGENTA"
echo -e "==================== Dos2Unix ===================="
echo -e "$DEFAULT"
i=1
while [ $i -le $CantPruebas ]
do
        cat  testFiles/testCaseSol$i | ./dos2unix > testFiles/testCaseRes2.$i
        DIFF=$(diff testFiles/testCase$i  testFiles/testCaseRes2.$i)
        if [ "$DIFF" == "" ]
        then
            echo -e "Test $i $GREEN"
	    echo -e "Ok"
	    echo -e "$DEFAULT"
        fi

        if [ "$DIFF" != "" ]
        then
            echo -e "Test $i $RED"
	    echo -e "Ok"
	    echo -e "$DEFAULT"
        fi
        i=$(( $i + 1 ))
done

